<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework>net6.0</TargetFramework>
      <Nullable>enable</Nullable>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
      <Reference Include="BepInEx.Unity.IL2CPP">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\BepInEx.Unity.IL2CPP.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="BepInEx.Core">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\BepInEx.Core.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="Il2CppInterop.Runtime">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\Il2CppInterop.Runtime.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\UnityEngine.CoreModule.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\UnityEngine.AssetBundleModule.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\UnityEngine.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="Il2Cppmscorlib">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\Il2Cppmscorlib.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="0Harmony">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\0Harmony.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\Assembly-CSharp.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\UnityEngine.InputLegacyModule.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="UnityEngine.PhysicsModule">
        <HintPath>$(MSBuildProjectDirectory)\..\libs\UnityEngine.PhysicsModule.dll</HintPath>
        <Private>false</Private>
      </Reference>
    </ItemGroup>
  </Project>
